### ISSUE TITLE
Requested col out of range

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#10]
Seeing access to out of range column in one of my events
`what():  Requested col for y=2400 ... but the y (cols) spans only 2400 => 8448!`

stdout:
https://gist.github.com/vgenty/2e0cc7e5b9c49b00a25ed93752f220e9

gdb:
https://gist.github.com/vgenty/2e6924b9d7a5a39cf76cd58c23e4c8a7

frame 7:
https://gist.github.com/vgenty/78c089052633781fe3b3f4b312f268b9

`tick_target` is optimized out... but if I dump the meta:

`(gdb) p meta.dump()`
`$2 = "Plane 0 (rows,cols) = (1008,3456) ... Left Top (0,8448) ... Right Bottom (3456,2400)\n"`

here is the offending event:
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again_x3.tar

**Comment by twongjirad** [comment]
does invalid mean the code is ok? or this is someting I should fix?

**Comment by vgenty** [comment]
If you could take a look that would be great. I chose the wrong label, my bad

**Comment by twongjirad** [comment]
This bug was in the Flash Bounary tagger and arose because an anode flash happen to occur at tick 2400. This is right at the boundary of the image and was mistakenly accepted. Now flashes at tick 2400 are not considered.

**Comment by vgenty** [comment]
Do you foresee this impacting the tagger performance at all? It seems like it would remove a potentially necessary boundary point.

**Comment by twongjirad** [comment]
While the tagger would not label the end as an anode track, it should, in principle, pick it up as an image-end boundary.
