### ISSUE TITLE
BoundaryEndPt error

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#11]
Running the tagger this evening, seeing an issue running on nu_mu sample

`what():  /home/vgenty/sw/larlitecv/build/include/TaggerTypes/BoundaryEndPt.h:24 invalues row (546) and/or col (-1) values provided`

stdout
https://gist.github.com/vgenty/d02ed000c77544ae18dbef7d31dc5b5c

gdb with f 6
https://gist.github.com/vgenty/e447fc3de29cc764a63f297d0438a5c1

the single event
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again_x4.tar

**Comment by twongjirad** [comment]
FoxTrot algo put point on positive z boundary.  It caused the point, when projected back into the images to be outside the bounds.  Did a bad quick fix for now, bumping boundary value inward by -0.3 cm.  Fixes issue.

**Comment by vgenty** [comment]
I think i'm experiencing a similar error on the latest larlitecv build

stdout:
https://gist.github.com/vgenty/54c4dd0804a120d5dc67c3d4a71128ac

bt with f 6 f 7
https://gist.github.com/vgenty/01d9647acf0323452501e3073b24d9f0
the

**Comment by barnchri** [comment]
This change is described in a Pull Request and is currently contained in branch 'BoundarySpacePt_StopMuFoxTrot_error'.

**Comment by twongjirad** [comment]
I confirm that this event works with Chris' fix in.
