### ISSUE TITLE
ThruMuFoxExtender error

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#12]
Seeing an issue in the tagger in ThruMuFoxExtender class @ runtime

stdout
https://gist.github.com/vgenty/6553d07fbb52a9e0a514ef627f0edc30

gdb bt & frame 6
https://gist.github.com/vgenty/c0a616dcc8b6fd1a82998848111fc84a

Please find the offending event attached here
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again_x5.tar

**Comment by barnchri** [comment]
I added a check in 'ThruMuTracker.cxx' and 'AStarNodes2BMTrackCluster3D.cxx' that the 3D points being added to the track convert to 2D Image points that are within the image (within 0 and the number of rows/cols, which depends on the image dimensions). Commit 'e2c1e8e'.
