### ISSUE TITLE
Empty Path in T3DCluster

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#15]
Sorry for always bugging... finding an error in _many_ of my events in the nu_mu sample

```
Terminate called after throwing an instance of 'std::runtime_error'
  what():  Empty Path in T3DCluster!
```

stdout:
https://gist.github.com/vgenty/6982b46511a0a005b89d7a221eadfcae

bt:
https://gist.github.com/vgenty/52e47f232a4a49d95c31c33dad9b7cc9

the offending file:
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again_x6.tar

**Comment by barnchri** [comment]
I ran the latest version of the tagger on a ten-event sample of extbnb events and everything was reconstructed well.  I will send you my sample to test.

**Comment by vgenty** [comment]
thanks @barnchri for confirming this is a non issue upon a fresh build
