### ISSUE TITLE
Out of bounds col for image

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#7]
I'm having a problem getting the tagger to run on my cosmic files. The error is:
`terminate called after throwing an instance of 'larcv::larbys'
  what():  Requested col for x=3456 ... but the x (rows) span only 0 => 3456!`

Here is the full stdout
https://gist.github.com/vgenty/e2a1dceb15a530fb43c3f16ff101be97

and gdb trace
https://gist.github.com/vgenty/2bb9fa9ad764c32e610dec6b54531634

with an error in `larlitecv::BMTrackCluster3D::getTrackPixelsFromImages` @ frame 7
https://gist.github.com/vgenty/4d5fb2229f450c818f7bdad34cc7141d

To reproduce this error please find this tarball (4.5M) containing the single event of interest
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug.tar

& what's inside
https://gist.github.com/vgenty/65a6ae3b07b98ea434ecaeb23c3a578f

**Comment by twongjirad** [comment]
Thanks, @vgenty, for the debug info! Made fixing this very easy.  Maybe we will have to write a tutorial about how to prep bug error like this. Anyway, I fixed this I think. Please update the repo and give it a try.
