### ISSUE TITLE
GeoAlgoException

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#9]
I have an event here which throws a `geoalgo::GeoAlgoException()` with `what()`

`<<EXCEPTION>> <<check_and_raise>> Two identical points not allowed for Line ctor!`

stdout
https://gist.github.com/vgenty/597bc064f8b8727e4ed9bfe1e0ec3ecc

gdb bt
https://gist.github.com/vgenty/116ed99e03ac3a3189eca09e9238a684

@ stack frame 9
https://gist.github.com/vgenty/6d05d4b9b0a0bbf4bc27ab5494ebe079

if I print out the start and end point of this line they are the same, raising this geoalgo exception
https://gist.github.com/vgenty/869275462b5d467110b394b060389fa8

Here is the culprit event
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again_again.tar

Thanks for taking a look!

**Comment by twongjirad** [comment]
This issue came was due to the stopping muon tagger.  It was traveling down a path of charge, then turned around and traveled back to the start.  I fixed this cause by having the tracker tag pixels it has already been to.  This prevents the backtracking.

**Comment by vgenty** [comment]
Experiencing this issue again on the latest larlitecv build

stdout
https://gist.github.com/vgenty/43f4d53ef19d66a066d0589c5635e8f6

bt 
https://gist.github.com/vgenty/21f68b617d7c4b24c5a95cd2656d29de

the single event
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again_x7.tar

**Comment by vgenty** [comment]
oops forgot to re-open, it's open @barnchri

**Comment by barnchri** [comment]
This change is described in a Pull Request and is currently contained in branch 'T3DPCMerge_Error_Solution'.

**Comment by twongjirad** [comment]
Fixed. In addition to Chris' solution, I had put an edge checker into UBWireTool and made a mistake about the start of the max_x (wire) boundary. I fixed that. This requires bumping LArCV. 

Note the event takes over a minute to reco... This is a good event to understand why long reco times occur.
